#include <stdio.h>
#include "platform.h"
#include "xparameters.h"
#include "xgpio.h"
#include "xil_io.h"
#include "xil_printf.h"

/* 
 * NOTE: The exact DEVICE_ID and BASEADDR macros will depend on your 
 * xparameters.h generated by Vitis. Update these to match your design.
 */
// #define GPIO_GAINS_ID XPAR_AXI_GPIO_GAINS_DEVICE_ID
// #define GPIO_SEL_ID   XPAR_AXI_GPIO_SEL_DEVICE_ID

// #define DDS_ASK_BASEADDR XPAR_ASK_MODULATOR_S_AXI_PHASE_BASEADDR
// #define DDS_OOK_BASEADDR XPAR_OOK_MODULATOR_S_AXI_PHASE_BASEADDR

// #define BRAM_DATA1_BASEADDR XPAR_AXI_BRAM_CTRL_0_S_AXI_BASEADDR
// #define BRAM_MAPPER_BASEADDR XPAR_AXI_BRAM_CTRL_1_S_AXI_BASEADDR

XGpio GpioGains;
XGpio GpioSel;

void set_gains(u16 gain_ask, u16 gain_ook) {
    // Channel 1 is ASK gain, Channel 2 is OOK gain
    // XGpio_DiscreteWrite(&GpioGains, 1, gain_ask);
    // XGpio_DiscreteWrite(&GpioGains, 2, gain_ook);
}

void set_mux_sel(u8 sel) {
    // XGpio_DiscreteWrite(&GpioSel, 1, sel);
}

void set_dds_freq(u32 base_addr, u32 phase_inc) {
    // Xil_Out32(base_addr, phase_inc);
}

void write_bram(u32 base_addr, u32 offset, u32 data) {
    // Xil_Out32(base_addr + offset, data);
}

int main() {
    init_platform();
    print("Project 2: FDM ASK/OOK PS Configuration\n\r");
    
    /* Initialize GPIOs */
    /*
    int status;
    status = XGpio_Initialize(&GpioGains, GPIO_GAINS_ID);
    if (status != XST_SUCCESS) {
        print("GPIO Gains Init Failed\n\r");
        return XST_FAILURE;
    }
    
    status = XGpio_Initialize(&GpioSel, GPIO_SEL_ID);
    if (status != XST_SUCCESS) {
        print("GPIO Sel Init Failed\n\r");
        return XST_FAILURE;
    }
    
    XGpio_SetDataDirection(&GpioGains, 1, 0x0); // Output
    XGpio_SetDataDirection(&GpioGains, 2, 0x0); // Output
    XGpio_SetDataDirection(&GpioSel, 1, 0x0);   // Output
    */
    
    // Set initial gains to 1.0 (assuming 1Q15 format or similar)
    set_gains(0x1FFF, 0x1FFF);
    
    // Set initial MUX sel to output of adder or FIR
    set_mux_sel(4); 
    
    // Example: Configure 2ASK vs 4ASK in BRAM
    // write_bram(BRAM_MAPPER_BASEADDR, 0x00, 0x0000); 
    // write_bram(BRAM_MAPPER_BASEADDR, 0x04, 0x7FFF); 
    
    // Example: Update DDS frequency
    // set_dds_freq(DDS_ASK_BASEADDR, 0x0A3D70A3); // Example phase increment
    
    print("Initialization complete. Entering interactive menu...\n\r");
    while(1) {
        // Implement UART menu to read keys and change configurations
    }
    
    cleanup_platform();
    return 0;
}
